name: Weekly WordPress Blog Post
on: [workflow_dispatch, push]

jobs:
  post-to-wordpress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run script
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
        run: python bristol_dental_auto_post.py
